#include "pumpkin.h"

/*
* Bootstrap exists as the project which will become the final executable for a
* game when it's built from the editor.
* 
* Pumpkin, Renderer, and Common are all static libraries. Editor is an executable for
* making the game's starting state and attaching scripts to nodes. Bootstrap is an
* executable which will be the final game executable.
*/
int main()
{
    pmk::Pumpkin pumpkin{};

	// Here we will call a function generated by the editor that loads in all the
	// assets needed by the game, and all the scripts etc.
	
    pumpkin.Start();

	return 0;
}
